# -*- coding: utf-8 -*-
"""liga_portugal_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16lvSowH6D1ajSFMeCWXrTeRxsb4qiGrW
"""

#!pip install streamlit # installing streamlit in jupyter if not installed 

import pandas as pd
import streamlit as st

# read excel file that contains the data of the app
#---------------------------------------------------------------------
df = pd.read_excel("liga_pt.xlsx").sort_values(by=['Name']).round(3)
#--------------------------------------------------------------------

#    editing the player column
#-----------------------------------
dfplayer = df['Name']
dflistp = dfplayer.values.tolist()
playerlist = []
for j in dflistp:
     playerlist.append(j)
df['Name']=playerlist
#------------------------------------

#            TITLE
#------------------------------------
title = "Player dashboard"
#-------------------------------------

#            LAYOUT
#-------------------------------------
st.set_page_config(layout="wide") 
#-------------------------------------

#      DISPLAYING THE TITLE
#--------------------------------------
st.title(title)
#--------------------------------------

# import and display image
#------------------------------
from PIL import Image
img = Image.open("ligapt.png")
st.image(img, width=300)
#-----------------------------

# horizontal line to separate the content
#------------------------------------------
st.markdown("***")
#-------------------------------------------

# display string
#-------------------------------------------------------------------------------------
st.write("Let's check some player stats of Liga Bwin 2021/22. Data from Soccerment.")
#-------------------------------------------------------------------------------------

# sidebar with filter for players
#------------------------------------------------------------------------------------
st.sidebar.header("Please Filter Here:")
name = st.sidebar.selectbox(
    "Select or write player name:\nPlayer names are sorted alphabetically.",
    options=df["Name"].unique()
)
df_selection = df.query(
    "Name == @name"
)
#-----------------------------------------------------------------------------------

# selecting stats from the data that will be displayed
team = df_selection["Team"].sum()
age = (df_selection["Age"].sum()).astype(int)
role = df_selection["Position"].sum()
time = df_selection["Time Played"].sum()
appearances = df_selection["Appearances"].sum()
goals = df_selection["Goals_p90"].sum()
xG = df_selection["xG_p90"].sum()
assists = df_selection["Assists_p90"].sum()
xA = df_selection["xA_p90"].sum()
xT = df_selection["xThreat_p90"].sum()
#--------------------------------------------------------------------

# displaying the selected stats inside columns
column0,column1,column2,column3,column7 = st.columns(5)
with column0:
     st.subheader("Team")
     st.subheader(f"{team}")
with column1:
     st.subheader("Age")
     st.subheader(f"{age}")
with column2:
     st.subheader("Role")
     st.subheader(f"{role}")
with column3:
     st.subheader("Appearances")
     st.subheader(f"{appearances}")
with column7:
     st.subheader("Time played")
     st.subheader(f"{time}")
    
#-----------------------------------------------------
st.markdown("***")
#-----------------------------------------------------

column4,column5,column6,column8,column9 = st.columns(5)
with column4:
     st.subheader("Goals/90")
     st.subheader(f"{goals}")
with column5:
     st.subheader("xG/90")
     st.subheader(f"{xG}")
with column6:
     st.subheader("Assists/90")
     st.subheader(f"{assists}")
with column8:
     st.subheader("xA/90")
     st.subheader(f"{xA}")
with column9:
     st.subheader("xT/90")
     st.subheader(f"{xT}")
    
#------------------------------------------------------------

st.write("https://www.linkedin.com/in/ricardoandreom/")
st.write("Date: 31/08/2022")
#-----------------------------------------------------------
#img = Image.open("halfspace_analytics.png")
#st.image(img, width=300)
#--------------------------------------------------------------